maxNameLength=15
maxLastNameLength=12
minNameLength=2
minLastNameLength=3
maxPrice=9000000
app.language=en
output.people=people.csv
output.product=products.csv
output.accounting=accounting.csv
output.path=data/
app.external.config=resources/config.properties
pagination.size=9
description.format=capitalize